### ISSUE TITLE
Not able to select only "type" values from events

### ISSUE THREAD

**Issue by lsabalo** [agrif/OctoPrint-InfluxDB#17]
Trying to build a Grafana dashboard and want to add a Log panel with the events type, but when I query only the "type", it returns black, but if I add another field, "type" is shown up but only on entries from the other field.

With "type" only:
```
> select type from events
>
```

With "t", "type":
```
> select t, type from events
name: events
time                t type
----                - ----
1598397385253106000 0 PositionUpdate
1598397408019018000 0 PositionUpdate
```

But only shows 2 entries (where "t" has a value, but "type" has more entries that are not being showed up.
Is this because "type" is a keyword for InfluxDB?

**Comment by lsabalo** [comment]
Got my own answer, "type" is a tag, not a field. My bad.

**Comment by agrif** [comment]
Glad you found an answer! I have difficulty sometimes deciding what should be tags. I think I expected people would want to filter on event type.
