### ISSUE TITLE
InfluxDB 2 compatibility?

### ISSUE THREAD

**Issue by ZeGuigui** [agrif/OctoPrint-InfluxDB#21]
From the settings I believe this is not InfluxDB 2 compatible?

Could you add settings for InfluxDB 2 (bucket, token...)

Thanks

**Comment by jbuck2005** [comment]
I second  this request !!

**Comment by kaciker** [comment]
+1 .InluxDB v2 is the present ¡¡ we need the update  :P

**Comment by wuast94** [comment]
Prometheus would be compatible too. You can import Prometheus nativ in influxdb2

But creating dashboards in grafana is not the yellow from the egg 😅

**Comment by agrif** [comment]
I've just released version 1.4.0, with influx 2.0 support (thanks to #25). Please open a new issue if you run into any problems -- I tested it a fair amount before releasing it, but it's still a large change, and I'm a caveman who hasn't upgraded to 2.x yet myself.
