### ISSUE TITLE
Plugin stops reporting after a few minutes (1.4.0 specific issue)

### ISSUE THREAD

**Issue by plampix** [agrif/OctoPrint-InfluxDB#28]
Since upgrading to 1.4.0, octoprint reports temperatures, until I start a print. Then it just stops sending, even when print is finished. Restart of octoprint solves the issue (until I start another print of course).

Happens on 3 of my octoprint installs.

Reverting to 1.3.2 everything works as expected again.

One of my co-workers also experiences this issue.

But 1.4.0 does seem to work on another printer. Same octoprint version, exactly the same plugins installed. 

Is it just me, or do other people have this issue as well?

**Comment by phoenix79** [comment]
I am having the same issue

**Comment by bkralik** [comment]
Hi, I have created the fix for this issue (nothing fancy, just verifying that the filament data really exists)
https://github.com/agrif/OctoPrint-InfluxDB/pull/29

**Comment by agrif** [comment]
I've merged this PR and released it in 1.4.1. If this issue continues, please open a new issue!

Thanks again to @bkralik for tracking this down.
