### ISSUE TITLE
Blank config dialog

### ISSUE THREAD

**Issue by danodemano** [agrif/OctoPrint-InfluxDB#3]
Octoprint Version 1.3.12

InfluxDB Plugin Version 1.0.0

The config dialog for this plugin is totally blank:

![image](https://user-images.githubusercontent.com/1128744/68264492-f5b85400-0016-11ea-8166-25bc43561454.png)

Tried multiple browsers, flushed cache, still blank.  If you need additional information please let me know.

**Comment by agrif** [comment]
That is very odd. Works fine on that combination here.

What change have you made to make the settings panel dark? It's possible that that is interacting poorly with the settings panel.

**Comment by danodemano** [comment]
Themeify was providing the dark theme which I just disabled, same thing:

![image](https://user-images.githubusercontent.com/1128744/68311377-7743cc80-007f-11ea-8aa9-3d1f52c0faad.png)

**Comment by danodemano** [comment]
I lied, disabling the theme wasn't enough.  I had to entirely disable the plugin:

![image](https://user-images.githubusercontent.com/1128744/68311646-d3a6ec00-007f-11ea-8e24-a5e1aabf08be.png)


What's odd is (as you can see) I have a bunch of other plugins and none of them have been an issue with that dark theme.

**Comment by danodemano** [comment]
Yeah I guess I wouldn't really worry too much about it since it seems to be fine now.  I do tend to encounter some of the oddest issues.  Thanks for the plugin by the way!  Hope to try it out tonight.

**Comment by agrif** [comment]
After looking around, the only thing I can imagine that would cause this is that OctoPrint needs a restart after installing the InfluxDB plugin, and somehow that didn't happen. But disabling Themeify would have forced a restart and fixed it.

Unless somebody else sees this problem, I don't think I'll be able to find out more. But thank you for the info!

**Comment by shortword** [comment]
FYI: I ran in to a very similar issue. No Themify, though I did have Dark Reader, Privacy Badger, and uBlock Origin installed. I tried a number of things "disable / enable," "uninstall / reinstall," private mode browsing, etc. I had to manually select the 'Restart OctoPrint' even after the install-triggered restart to get it to show up. Hopefully this helps someone if they run in to the same issue.
