### ISSUE TITLE
[Enhancement] Store generic values via EventListener

### ISSUE THREAD

**Issue by OllisGit** [agrif/OctoPrint-InfluxDB#5]
Hi @agrif ,

I like your plugin very much.

I want to use your plugin to store a lot of other values beside the currently implemented. E.g. user-information, layer height, durations, ...
My idea is that your plugin could implement a pre defined event-listener. Each time an event is received (send from other plugins), the event payload is parsed and values were stored into the influx db.

What do you think?
Olli

**Comment by agrif** [comment]
I think it's a good idea, but I'm a little bit wary of just dumping every received event into Influx. For starters, it's not clear what event fields should be tags, and which should be values.

I am interested in expanding the amount of information the plugin records, though, and if we can figure out a reasonable way to handle more events automatically, I'm on board. In the meantime, I'll probably be extending it to layer height and other similar info during the holidays.

**Comment by agrif** [comment]
I've looked over the existing OctoPrint events and decided there's probably no harm in just recording them all in Influx. Please upgrade to the (newly-released) 1.2.0 and test it out!
