### ISSUE TITLE
Plugin may cause instability when using Prusa MK3s with MMUs and SD card printing

### ISSUE THREAD

**Issue by m00dawg** [agrif/OctoPrint-InfluxDB#7]
I've been chasing down a situation where doing multiple prints from the SD card (as in starting the print right from the printer's display) seems to cause OctoPrint to either disconnect from the printer or, in some cases, crash.

This behavior seems to be if the InfluxDB plugin is enabled. If I disable the plugin, the issue disappears.

Version: 1.0.2

Steps to reproduce:

- Enable InfluxDB Plugin
- Start an MMU2 single filament print from the printer using the SD card
- Upon completion, start another print (in my case I used the exact same model)
- Open Octo UI. It will either show the printer as disconnected, or will not be updating printer stats, or, in some tests, just completely crashes the UI requiring a restart

I haven't yet figured out why this may be taking place. I do wanna say it's pretty recent, however. Within the last few weeks or months.

**Comment by agrif** [comment]
That is perplexing. I'm not sure what I could be doing that causes the printer to disconnect -- I shouldn't be doing anything but reading data!

Can you check your logs to see if anything suspicious is printed when this happens?

**Comment by m00dawg** [comment]
Doh good point I forgot to look at the logs. Yep let me re-enable it and see what happens over the next prints I'll be doing.

**Comment by m00dawg** [comment]
Right? I thought that was weird too. It did seem to remedy itself once I disabled the plugin. However since re-enabling it, it's been working like a champ - I haven't had a single problem in several prints. So I think disabling/re-enabling somehow fixed...something? So yep I'm gonna close this out for now since it looks to be working well. Sorry to bug ya!

**Comment by agrif** [comment]
Well, if you run into it again and figure something out, let me know! Glad it’s working now, anyway.
