### ISSUE TITLE
enhancement: record enclosure temp

### ISSUE THREAD

**Issue by petitxef** [agrif/OctoPrint-InfluxDB#8]
Hi!
I'm wondering if it's possible to add the enclosure temps on this plugin.

I'm using a BME280 sensor (using octoprint-Enclosure plugin) and it'll be a nice enhancement.

Thanks!

**Comment by agrif** [comment]
Possibly -- are enclosure temperatures something OctoPrint can read out of the box? or only with this plugin? I think it can work both ways, but I've never used enclosure sensors before, so I'm unfamiliar with how this works.

**Comment by petitxef** [comment]
Hi!
I’m not familiar with programming, but the octoprint-enclosure plugin use the I2C:

https://github.com/vitormhenrique/OctoPrint-Enclosure/blob/master/README.md

**Comment by agrif** [comment]
This looks possible -- OctoPrint-Enclosure sends out [some events I can hook into](https://github.com/vitormhenrique/OctoPrint-Enclosure/blob/master/octoprint_enclosure/__init__.py#L711-L720). So it's just a matter of finding time to set up a test server and get it working. I'll try to do that this week, but if I take much longer feel free to poke me about it.

**Comment by petitxef** [comment]
Thanks for your time!

**Comment by petitxef** [comment]
Hi Agrif!

Just a remind with this improvement!

Thanks!

**Comment by agrif** [comment]
Things are taking a little bit longer than expected -- that OctoPrint plugin refuses to even load on anything other than a raspberry pi, even if you only intend to use it with the virtual debug sensors :(

**Comment by petitxef** [comment]
Ok, so don’t worry, don’t spend more time, just thought was much easier :)
Thanks anyway
